import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import RootLayout from "./layout";
import { FaXTwitter } from "react-icons/fa6";
import { FaLinkedinIn } from "react-icons/fa";
import { FaInstagram } from "react-icons/fa6";
import Image from "next/image";
import { Carousel } from "react-responsive-carousel";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { delay, motion, useInView } from "framer-motion";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/router";

const textVariants = {
  hidden: { opacity: 0 },
  visible: (i: number) => ({
    opacity: 1,
    transition: {
      delay: i * 0.03, // Waktu delay per huruf
    },
  }),
};

const sentence = {
  text: "Hi, my name is",
  style: "text-sm md:text-md text-[#8892B0] font-popp ",
};
const name = {
  text: "July Dwi Saputra.",
  style: "text-xl md:text-5xl font-bold text-[#CBD5F5] mb-2 font-popp ",
};
const role = {
  text: "I'm Front-End Developer.",
  style: "text-lg md:text-4xl font-semibold text-[#8892B0] mb-2 font-popp",
};
const description = {
  text: "I’m a frontend web developer with extensive experience for over 2 years. My expertise is to create and websites design.",
  style: "text-sm md:text-md text-[#8892B0] font-light font-popp",
};

const TypingAnimation = ({ text, style }: { text: string; style: string }) => (
  <div className="overflow-hidden">
    {text.split("").map((letter, i) => (
      <motion.span
        key={i}
        custom={i}
        variants={textVariants}
        initial="hidden"
        animate="visible"
        className={`inline-block overflow-hidden font-mons ${style}`}
        style={{ whiteSpace: "pre" }}
      >
        {letter}
      </motion.span>
    ))}
  </div>
);

const ProfileAbouteMe = () => {
  const ref = useRef(null);

  const inView = useInView(ref, {
    once: true,
  });

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, scale: 0.2, translateX: "100px", translateY:"-100px" }}
      animate={{ opacity: inView ? 1 : 0, scale: inView ? 1 : 0.2, translateX: inView ? 0 : "100px", translateY: inView ? "0" : "-100px" }}
      transition={{ delay: 0.2, duration: 1 }}
      className="relative w-[280px] h-[280px] md:max-h-[300px] md:max-w-[300px] md:top-44 lg:top-0 lg:max-w-[350px] lg:max-h-[350px] border-[#8892B0] border-2 border-dashed flex flex-col justify-center items-center rounded-full bottom-20 lg:bottom-0 duration-700">
      <Image className="absolute bottom-[20px]  md:bottom-5 rounded-full w-[240px] h-[240px] object-cover object-top" src="/12210977.jpg" width={800} height={800} objectFit="cover" alt="profile-1" />
    </motion.div>
  )
}

const DescAbouteMe = () => {
  const ref = useRef(null);

  const inView = useInView(ref, {
    once: true,
  })


  const router = useRouter()
  useEffect(() => {
    if (router.query.scrollTo === "about") {
      const aboutSection = document.getElementById("aboute");
      if (aboutSection) {
        aboutSection.scrollIntoView({ behavior: "smooth", block: "start" });
      }
    }
  }, [router.query]);

  return (
    <motion.div
      ref={ref}
      initial={{  opacity: 0, translateY: "100px" }}
      animate={{  opacity: inView ? 1 : 0, translateY: inView ? 0 : "100px" }}
      transition={{ delay: 1.2, duration: 1 }}
      className="flex w-[85%] md:w-full lg:w-2/4 flex-col gap-5 justify-start items-end md:items-center text-white">
      <h1 className="font-semibold text-xl md:text-5xl text-[#CBD5F5] text-right md:text-center font-popp">About Me</h1>
      <p className="text-[#8892B0] font-light text-sm/7 text-justify md:text-center font-popp">Saya seorang fresh graduate D3 Sistem Informasi yang berhasil lulus dengan IPK 3.94 di Universitas Bina Sarana Informatika Kampus Kota Surakarta. Saya lahir di Sukoharjo, 4 juli 2003 yang saat ini telah meninjak usia 21 tahun.<br/> <br/> Pengalaman magang, bekerja,dan berorganisasi yang pernah saya alami semasa berkuliah secara tidak langsung dapat meningkatkan skill dan wawasan saya, sehingga sekarang menjadikan saya seorang Front End Web Developer yang sangat tertarik untuk belajar hal" baru.</p>
      <hr className="h-[2px] w-3/4 bg-[#8892B0] border-none" />
    </motion.div>
  )
}

const Index: NextPage = () => {
  const [autoPlay, setAutoPlay] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => {
      setAutoPlay(true);
    }, 5000);

    return () => clearTimeout(timer);
  }, []);


  return (
    <>
      <Head>
        <title>JULY DWI SAPUTRA | FRONTEND DEVELOPER</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>

      <RootLayout>
        <div className="relative w-full h-screen flex flex-row-reverse">
          <div className="w-full flex flex-col-reverse relative">
            <div className="relative md:pl-24 lg:pl-32 w-full md:w-3/4 lg:w-full h-screen pt-10 md:pt-20 ">
              <div className="absolute flex flex-col items-start z-30 w-full h-screen ">
                <div className="hover:translate-x-5 duration-1000">
                  <TypingAnimation
                    text={sentence.text}
                    style={sentence.style}
                  />
                </div>
                <div className="hover:-translate-x-5 duration-1000">
                  <TypingAnimation text={name.text} style={name.style} />
                </div>
                <div className="hover:translate-x-5 duration-1000">
                  <TypingAnimation text={role.text} style={role.style} />
                </div>
                <div className="w-full md:w-1/2 hover:-translate-x-5 duration-1000">
                  <TypingAnimation
                    text={description.text}
                    style={description.style}
                  />
                </div>
                <motion.div
                  initial={{ opacity: 0, scaleY: 0 }}
                  animate={{ opacity: 1, scaleY: 1 }}
                  transition={{ delay: 3, duration: 0.8 }}
                  className="w-full"
                >
                  <button className="hover:scale-110 duration-500 border-solid border-2 border-[#8892B0] rounded-md px-3 py-2 font-mons font-medium text-sm text-[#8892B0] my-4">
                    Resume
                  </button>
                </motion.div>

                <div className="flex flex-col md:flex-row w-full justify-start items-start  gap-2 md:gap-5 lg:absolute lg:bottom-[260px] hover:translate-x-10 duration-700 ">
                  <motion.div
                    initial={{ opacity: 0, x: -100 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 4, duration: 0.8 }}
                    className="w-full"
                  >
                    <Link
                      href="/blabla"
                      className="font-mons text-xs md:text-md font-medium text-[#8892B0]"
                    >
                      julydsp@gmail.com
                    </Link>
                    <hr className="bg-[#8892B0] w-full border-none h-[2px]" />
                  </motion.div>
                </div>
              </div>

              <div className="absolute bottom-0 right-0 flex justify-end items-center md:w-1/2 lg:z-30 z-30">
                <motion.div
                  initial={{ opacity: 0, y: 300 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 5.5, duration: 0.8 }}
                >
                  <Carousel
                    showArrows={false}
                    showThumbs={false}
                    showStatus={false}
                    showIndicators={false}
                    infiniteLoop
                    autoPlay={autoPlay}
                    axis="horizontal"
                    interval={3000}
                    transitionTime={1000}
                    stopOnHover={false}
                    emulateTouch={false}
                    swipeable={false}
                    className="relative w-[600px] h-[750px] md:w-[800px] md:h-[1000px] bg-center object-cover bottom-0 -right-44 md:-right-64  lg:-right-20 "
                  >
                    <div className="fade-slide">
                      <Image
                        src={"/profile-1.png"}
                        alt="Profile Image 1"
                        width={800}
                        height={1000}
                        objectFit="cover"
                      />
                    </div>
                    <div className="fade-slide">
                      <Image
                        src={"/profile-2.png"}
                        alt="Profile Image 2"
                        width={800}
                        height={1000}
                        objectFit="cover"
                      />
                    </div>
                    <div className="fade-slide">
                      <Image
                        src={"/profile-3.png"}
                        alt="Profile Image 3"
                        width={800}
                        height={1000}
                        objectFit="cover"
                      />
                    </div>
                  </Carousel>
                </motion.div>
              </div>
            </div>
          </div>

          <motion.div
            initial={{ opacity: 0, y: 150 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 5, duration: 0.8 }}
          >
            <div className="h-screen fixed z-50">
              <ul className="absolute flex flex-col gap-5 left-0 bottom-60 z-40">
                <Link
                  href="https://x.com/_julydsp"
                  className="hover:scale-125 duration-700 hover:rotate-[360deg]"
                >
                  <FaXTwitter className="text-[#CBD5F5] text-xl " />
                </Link>
                <Link
                  href="https://www.linkedin.com/in/julydsp"
                  className="hover:scale-125 duration-700 hover:rotate-[360deg]"
                >
                  <FaLinkedinIn className="text-[#CBD5F5] text-xl" />
                </Link>
                <Link
                  href="https://www.instagram.com/xjydsp"
                  className="hover:scale-125 duration-700 hover:rotate-[360deg]"
                >
                  <FaInstagram className="text-[#CBD5F5] text-xl" />
                </Link>
              </ul>
              <hr className="absolute bg-[#8892B0] border-none h-[2px] rotate-90 w-60 -left-[110px] bottom-20" />
            </div>
          </motion.div>
        </div>

      {/* ini adalah element aboute me */}
        <div  id="aboute" className="w-full relative h-screen mt-[280px] mb-5 md:p-10 flex flex-wrap-reverse flex-row-reverse md:flex-col-reverse lg:flex-row justify-start md:justify-around md:items-center">

          <div className="absolute bottom-0 right-0 w-full h-full bg-gradient-radial from-transparent via-transparent to-blue-500 opacity-30 "></div>
          <div className="absolute bottom-0 right-0 w-full h-full bg-gradient-to-tl from-blue-700 via-transparent to-transparent blur-[130px] opacity-80 "></div>

          <DescAbouteMe />
          <ProfileAbouteMe />

        </div>

        <div>
          
        </div>
      </RootLayout>
    </>
  );
};

export default Index;
